### ISSUE TITLE
Some key features not implemented - e.g. variable sets are not saved.

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#21] opened 2022-03-09 13:46 UTC
Sherri observed: "I went through and created a variable set, but don’t know how to find it now? It’s not under project catalogs. Is this because it is in the testing phase?"

Key features she noted as not implemented:

1. Variable sets not saved
2. Favorite variables
3. Variable context PDF

**Comment by Viqsi** [comment] 2022-03-09 13:48
Duplicate of #5.

**Comment by Viqsi** [comment] 2022-09-05 23:01
Item 2 is now tracked in issue #42, and item 3 is in issue #12, so this can be closed as a duplicate.

**Closed by Viqsi** 2022-09-05 23:01 UTC
Labels: duplicate, not yet implemented
