### ISSUE TITLE
Context showing incorrect variable DI-PAD vs DIGS?

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#22] opened 2022-03-09 13:54 UTC
Sherri observed: "I went through and created a variable set, but don’t know how to find it now? It’s not under project catalogs. Is this because it is in the testing phase?"

**Comment by WValenti** [comment] 2022-03-09 13:54
I need more information as I was under the impression that context display was not at all implemented.

**Comment by Viqsi** [comment] 2022-03-09 13:56
Variable sets haven't been implemented *at all* in the backend. It hasn't been saved, so no saved variable sets would show up afterward. The only variable sets that "show up" at all right now (if any) are fake ones provided by Annalisa's mockup.

**Comment by WValenti** [comment] 2022-03-09 13:59
Ah. So to state it explicitly, she may be asking for DI-PAD, but Annalisa's mockup is all that shows up and it is for DIGS.

**Comment by Viqsi** [comment] 2022-09-05 23:07
On re-review, this seems to be User Confusion w/r/t the state of variable sets. So, closing as a duplicate of #5.

**Closed by Viqsi** 2022-09-05 23:07 UTC
Labels: question, not yet implemented
